"""empty message

Revision ID: 1a44ce4c5a50
Revises: 806ecafcf80b
Create Date: 2018-03-10 16:31:54.960077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a44ce4c5a50'
down_revision = '806ecafcf80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resource_ibfk_4', 'resource', type_='foreignkey')
    op.drop_column('resource', 'attention_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('attention_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('resource_ibfk_4', 'resource', 'attention', ['attention_id'], ['id'])
    # ### end Alembic commands ###
