"""empty message

Revision ID: 4a846569cd01
Revises: 82fa73e69608
Create Date: 2018-03-14 15:57:04.871107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a846569cd01'
down_revision = '82fa73e69608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('url_info', sa.String(length=15), nullable=True))
    op.drop_column('resource', 'commentnum')
    op.drop_column('resource', 'downloadnum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('downloadnum', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('commentnum', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_column('resource', 'url_info')
    # ### end Alembic commands ###
