"""empty message

Revision ID: 90a36670be49
Revises: f83847b7a115
Create Date: 2018-02-26 15:19:11.448601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90a36670be49'
down_revision = 'f83847b7a115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('rs_type', sa.Text(), nullable=True))
    op.add_column('resource', sa.Column('url_type', sa.Text(), nullable=True))
    op.drop_column('resource', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('info', mysql.TEXT(), nullable=True))
    op.drop_column('resource', 'url_type')
    op.drop_column('resource', 'rs_type')
    # ### end Alembic commands ###
