"""empty message

Revision ID: a4d75d0152dd
Revises: 0f447d36e4ab
Create Date: 2018-03-10 16:02:46.434431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d75d0152dd'
down_revision = '0f447d36e4ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attention', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attention', 'user_id')
    # ### end Alembic commands ###
