"""empty message

Revision ID: c354f3a39ebf
Revises: f8616fcd4438
Create Date: 2018-03-09 15:41:13.206219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c354f3a39ebf'
down_revision = 'f8616fcd4438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attention', sa.Column('be_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attention', 'be_user_id')
    # ### end Alembic commands ###
