"""empty message

Revision ID: cd6e66fee76d
Revises: cafedaa06497
Create Date: 2018-02-04 12:19:50.204270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd6e66fee76d'
down_revision = 'cafedaa06497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attention_ibfk_1', 'attention', type_='foreignkey')
    op.drop_column('attention', 'beuser_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attention', sa.Column('beuser_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('attention_ibfk_1', 'attention', 'user', ['beuser_id'], ['id'])
    # ### end Alembic commands ###
